I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/takeshiscene.rpy", line 149, in script
    if t_section2_flag == 1:
  File "game/takeshiscene.rpy", line 149, in <module>
    if t_section2_flag == 1:
NameError: name 't_section2_flag' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/takeshiscene.rpy", line 149, in script
    if t_section2_flag == 1:
  File "renpy/ast.py", line 1898, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/takeshiscene.rpy", line 149, in <module>
    if t_section2_flag == 1:
NameError: name 't_section2_flag' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
EscapeTheBullpen 1.0
Wed Jul  6 15:02:07 2022
